#!/bin/bash

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* 14,15,16,17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        for country in AT BE CH DE-LU DK1 DK2 FI FR GB NL NO1 NO2 NO3 NO4 NO5 PL SE1 SE2 SE3 SE4 
        do
          export output_file=$(echo "${country}.html" | awk '{print tolower($0)}')
          yesterday=$(date --date="yesterday" +"%Y-%m-%d")
          today=$(date --date="today" +"%Y-%m-%d")
          curl "https://www.epexspot.com/en/market-data?market_area=${country}&trading_date=${yesterday}&delivery_date=${today}&underlying_year=&modality=Auction&sub_modality=DayAhead&product=60&data_mode=aggregated&period=" > "${output_file}"
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u --rfc-3339=seconds)
        git commit -m "Latest data (UTC): ${timestamp}" || exit 0
        git push
